services:
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
  rabbitMq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
