export enum AccommodationType {
  HOTEL = "hotel",
  VILLA = "villa",
  APARTMENT = "apartment",
  CABIN = "cabin",
  BUNGALOW = "bungalow",
  COTTAGE = "cottage",
  RESORT = "resort",
  GUEST_HOUSE = "guest_house",
  HOSTEL = "hostel",
  ROOM = "room",
  SHARED_SPACE = "shared_space",
  HOUSEBOAT = "houseboat",
  TREEHOUSE = "treehouse",
  CAVE = "cave",
  FARM_STAY = "farm_stay",
  TENT = "tent",
  CHALET = "chalet",
}

export enum SharedWith {
  OWNER = "owner",
  TENANT = "tenant",
  OTHER_GUESTS = "other_guests",
  STAFF = "staff",
  CLEANER = "cleaner",
  SECURITY = "security",
  NOBODY = "nobody",
}

export enum Amenities {
  WIFI = "wifi",
  AIR_CONDITIONING = "air_conditioning",
  HEATING = "heating",
  TV = "tv",
  KITCHEN = "kitchen",
  PARKING = "parking",
  SWIMMING_POOL = "swimming_pool",
  GYM = "gym",
  WASHING_MACHINE = "washing_machine",
  DRYER = "dryer",
  BREAKFAST_INCLUDED = "breakfast_included",
  PET_FRIENDLY = "pet_friendly",
  SMOKING_ALLOWED = "smoking_allowed",
  ELEVATOR = "elevator",
  WORKSPACE = "workspace",
  BALCONY = "balcony",
  SECURITY = "security",
  PRIVATE_BATHROOM = "private_bathroom",
  HOT_WATER = "hot_water",
  FIRE_EXTINGUISHER = "fire_extinguisher",
  FIRST_AID_KIT = "first_aid_kit",
}
